import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import marketRouter from "./market";
import indicatorsRouter from "./indicators";
import signalsRouter from "./signals";
import portfolioRouter from "./portfolio";
import ordersRouter from "./orders";
import botRouter from "./bot";
import capitalRouter from "./capital";
import backtestRouter from "./backtest";
import newsRouter from "./news";
import alertsRouter from "./alerts";
import bybitRealRouter from "./bybit-real";
import tanitRouter from "./tanit";
import tanitMastraRouter from "./tanit-mastra";
import threadsRouter from "./threads";
import audioRouter from "./audio";
import systemRouter from "./system";
import adminRouter from "./admin";
const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(marketRouter);
router.use(indicatorsRouter);
router.use(signalsRouter);
router.use(portfolioRouter);
router.use(ordersRouter);
router.use(botRouter);
router.use(capitalRouter);
router.use(backtestRouter);
router.use(newsRouter);
router.use(alertsRouter);
router.use(tanitRouter);
router.use(tanitMastraRouter);
router.use(threadsRouter);
router.use(audioRouter);
router.use(systemRouter);
router.use(adminRouter);
router.use("/bybit", bybitRealRouter);

export default router;
